spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "ENC(5nLoOfk4dRACENdmNbwbcQXIzYLa0LCefZ7jVyRHc9IsDrRg0Xg6RA3KVI5Vz0X0x7Z5tzuX/t/gNQcPwc2NI1xNNTKdpjdfiQnEtdTY1wBvExTtI2O8SCyioWxlnJARE/i18973MaoLRXssUBrpVL3t3IPPjKOtVw1hrfW9faZbZyXYXLi3TJxj//2M7Oeq32dhxx6ynR4hJip5yAoNWkEtsBSzogJyBXyJBUqbuFI=)"
    username: "ENC(vYods25swLvt5Z6V2ALldU05F6vZqoJFWpsFZjhZRAwUm/YgdiIXUlFMg707ScTW)"
    password: "ENC(lZkN3xnNZlLrNWCQF5Dnqlhk15oMBmfJKaunxpcs3H7Pa+LaAHJyTVK01CM7cCwx)"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: "ENC(GloiIVBPE4wJBAP1W5aKLENDsRNqWteNlqMYS1CLVyh0cS0+LRClOhB0vGiz2TF3/Dn5MPJ7Q+XyPVrgvS+CGg==)"  # 실제 암호화된 값으로 변경 필요
    password: "ENC(uV8bH41Me3imr/YpCmqOZTZ6gfoQr5MEiV6ZN72mIJUAcBmydBeS+oNcuz8CKP27Qtc4bPXK75SYYyNRGHL4mQ==)"   # 실제 암호화된 값으로 변경 필요
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jasypt:
  encryptor:
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    provider-name: BC
    password: "${JASYPT_ENCRYPTOR_PASSWORD}"
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

openai:
  api:
    key: "ENC(P+Q7qdYh2MoN9BouTHdG2P05ZzdZWe/8P9Zzic8XFmmEvph4t0MiiC3DLrnFnblhmDSq0gq7JbGx/dyjdPevPzwtA3RzMV9AG7k5NOPIqDJ6GBnIbT3fEWYKZ0on0DYckFhYA3405hVDcaMjL8ZghZfM2dOu/iHkvY57HR+PQPVuabKU81EfCweZmXlTJMKpNAadnjEBRLQdV0/EF1rA+fnMvo8TjJ3MqEH1PP714/cNO5Q4MhbC+FNyyNHUWk4tWLrqa0OQTM4IoozzQF0Brg==)"
    url: "https://api.openai.com/v1/chat/completions"
    model: "gpt-3.5-turbo"

ai:
  text:
    url: "${AI_TEXT_URL:http://host.docker.internal:8000}"
  image:
    url: "${AI_IMAGE_URL:http://host.docker.internal:8100}"

blender:
  server:
    url: "ENC(sHyKBP3rOgDDSeed4qZhcIZZgptJ8xgIPZKWG3GuvsZda8JSNEsrWSCGB9bVE3jEDAL2oq/a4JjtAexWhlDHyA==)"

papago:
  api:
    url: "ENC(G+ovwtS6yPOsLFm+Z+amWFvdB0a1Xs+VoX0oKujAIr3nw34/4ok0z1on2vgw2d7GurwHGyxa1K/z6Us8Wgln4oJpxBDsCcFZNbyBHYUKkMJ0HvzL/MOJfTHB0Vigal5C)"
    key:
      id: "ENC(RhUDCqRXXDeFaN3PCYuqA6PuxDOiexumVKXzdb8EVxDn0U2AnsE7XXYSonGaMlZk)"
      secret: "ENC(m/da7d/sCupZZp7H6KusFoHbaK/eLFMvuW472GldXJjXyjRFCpnazpZjbgEvWI23nZtcDGPzvhbT72sbDFtEK8jkvUJ/Jf20moSpXvrG3Rw=)"

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

cloud:
  aws:
    credentials:
      access-key: "ENC(QiSdfP2GduWlvif0YbPbss/L3YP5MXVxXe+xbJSsHL0SzWru2urnNLWFnLJRU4/FwX+CVWhEqrf8PJPhcOuTLw==)" # IAM 액세스 키
      secret-key: "ENC(qVfqdNcc0GQFAe5qPdl/txk6DssRPOzuGyymsb5E5Lv9w2XWzO59GrW2O8sQdHC4d89BKF1vzYrDap3iJa/5eXbY7ULX62sm+qGixbTN7Z4=)" # IAM 비밀 액세스 키
    s3:
      bucket: "ENC(F9iuNbNEY8SMboInVUM+Qsk2IfG/x0MCKHIm1SelZjZjsfM40sLe5B+2sWfEmtarJC1RNN0Edw8uxLApUVjUDA==)" # S3 버킷명
    region:
      static: "ENC(qTocIjMdJQSX5wojQE324QkRfDedjOD/n5QSZjb/Cja3SfrkuoSbrbvc+uXDIwYj)"
