spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "ENC(5nLoOfk4dRACENdmNbwbcQXIzYLa0LCefZ7jVyRHc9IsDrRg0Xg6RA3KVI5Vz0X0x7Z5tzuX/t/gNQcPwc2NI1xNNTKdpjdfiQnEtdTY1wBvExTtI2O8SCyioWxlnJARE/i18973MaoLRXssUBrpVL3t3IPPjKOtVw1hrfW9faZbZyXYXLi3TJxj//2M7Oeq32dhxx6ynR4hJip5yAoNWkEtsBSzogJyBXyJBUqbuFI=)"
    username: "ENC(vYods25swLvt5Z6V2ALldU05F6vZqoJFWpsFZjhZRAwUm/YgdiIXUlFMg707ScTW)"
    password: "ENC(lZkN3xnNZlLrNWCQF5Dnqlhk15oMBmfJKaunxpcs3H7Pa+LaAHJyTVK01CM7cCwx)"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jasypt:
  encryptor:
    algorithm: PBEWITHSHA256AND256BITAES-CBC-BC
    provider-name: BC
    password: "${JASYPT_ENCRYPTOR_PASSWORD}"
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

openai:
  api:
    key: "ENC(P+Q7qdYh2MoN9BouTHdG2P05ZzdZWe/8P9Zzic8XFmmEvph4t0MiiC3DLrnFnblhmDSq0gq7JbGx/dyjdPevPzwtA3RzMV9AG7k5NOPIqDJ6GBnIbT3fEWYKZ0on0DYckFhYA3405hVDcaMjL8ZghZfM2dOu/iHkvY57HR+PQPVuabKU81EfCweZmXlTJMKpNAadnjEBRLQdV0/EF1rA+fnMvo8TjJ3MqEH1PP714/cNO5Q4MhbC+FNyyNHUWk4tWLrqa0OQTM4IoozzQF0Brg==)"

ai:
  server:
    url: "ENC(jZwQeNXnLOYOKxAxfQGcehURWQXk2a9COw/hTeEJRuEaI8H2xExPD9BRmFRlzC5iT0h5gQx6EG6eCygibQyUyQ==)"

papago:
  api:
    url: "ENC(G+ovwtS6yPOsLFm+Z+amWFvdB0a1Xs+VoX0oKujAIr3nw34/4ok0z1on2vgw2d7GurwHGyxa1K/z6Us8Wgln4oJpxBDsCcFZNbyBHYUKkMJ0HvzL/MOJfTHB0Vigal5C)"
    key:
      id: "ENC(RhUDCqRXXDeFaN3PCYuqA6PuxDOiexumVKXzdb8EVxDn0U2AnsE7XXYSonGaMlZk)"
      secret: "ENC(m/da7d/sCupZZp7H6KusFoHbaK/eLFMvuW472GldXJjXyjRFCpnazpZjbgEvWI23nZtcDGPzvhbT72sbDFtEK8jkvUJ/Jf20moSpXvrG3Rw=)"

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: off
